### PR TITLE
Remove Shopee inline ads

### PR DESCRIPTION
**Pull request by toastal**
Gitmoji is tacky; I won't be using it.

### CODE REVIEW

**Comment by gluons** [comment]
Could you point out where the ads exist?

**Comment by toastal** [comment]
I just realized that `shopee.co.th##[data-sqe="ad"]:upward([data-sqe="item"])` could maybe be `shopee.co.th##[data-sqe="item"]:has([data-sqe="ad"])` if it's more performant.

The ads exist in every list/grid view. When you search a product, a lot of unrelated stuff products are displayed that don't help the search results.

**Comment by gluons** [comment]
[ภาพ](https://shopee.co.th/search?keyword=หน้ากากอนามัย)

I can't find any ads even I disable my uBlock.

Could you post some screenshot with ads and provide link to that page?

**Comment by toastal** [comment]
All are marked as "Ad" in a box. The ads are only like 15% correct for what I wanted when searching.

https://shopee.co.th/search?keyword=thunderbolt%204%20hub

Several items only USB 3.1 hubs and not Thunderbolt 3+ or USB4.

https://shopee.co.th/search?keyword=salomon

Had a row with different brands and a bed spread.

**Comment by midnight-wonderer** [comment]
`[data-sqe="ad"]` does not work anymore.

The following works for me:
`shopee.co.th##[data-sqe="item"]:has(img[loading="lazy"] ~ .right-0 > .text-white)`
but somewhat prone to changes as it relies on appearance-based classes.

P.S. `:upward` [does not work with Brave](https://github.com/brave/brave-browser/issues/16935) (yet).

**Comment by gluons** [comment]
Maybe fixed by #84

**Pull request closed without merging**
